export default function BlogPost() {
  return (
    <main>
      <article>
        <h1>Test Deploy Hooks Blog</h1>
        <div className="blog-meta">
          Generated by AI Blog Generator • August 12, 2025
        </div>
        <div dangerouslySetInnerHTML={{ __html: `<h1>Test Deploy Hooks Blog</h1>
<p>This is a test blog post to verify our deploy hooks are working correctly.</p>
<h2>Features</h2>
<ul>
<li>Automated GitHub repository creation</li>
<li>Instant Vercel deployment via API</li>
<li>Deploy hooks for future updates</li>
</ul>
<h2>Technology</h2>
<p>This blog was created using our enhanced deployment pipeline with Vercel deploy hooks.</p>` }} />
      </article>
    </main>
  )
}
